### ISSUE TITLE
Various errors (with screenshots)

### ISSUE THREAD

**Issue by eobet** [danielenger/Bake-to-Vertex-Color#1]
1. Attempt to bake several selected meshes at once:
![Capture](https://user-images.githubusercontent.com/3254196/73885070-644fbc80-4867-11ea-9974-9d9d11c98595.PNG)

2. Attempt to bake several selected meshes including an empty at once:
![Capture2](https://user-images.githubusercontent.com/3254196/73885157-9c56ff80-4867-11ea-937c-3ecb65c274d2.PNG)

3. Attempt to bake several selected meshes that already have vertex colors assigned, including an empty:
![Capture3](https://user-images.githubusercontent.com/3254196/73885351-e93ad600-4867-11ea-8128-476549d09b6d.PNG)

4. Attempt to bake several selected meshes (including empty) in edit mode:
![Capture1](https://user-images.githubusercontent.com/3254196/73886096-379ca480-4869-11ea-8d85-4bc91991f913.PNG)

Error number 3 did produce a result actually!

The only other way I can produce a result without any error is selecting one object at a time, but that sort of defeats the purpose of this add-on for me.

Hope you can look into this as it is exactly what I need at the moment!

PS. Why is the add-on panel hidden in the shader workspace side panel, and not in the main viewport side panel where add-ons normally reside? :)

**Comment by danielenger** [comment]
I totally missed your issue report from February!
I fixed it. Should work now. :grin:

**Comment by eobet** [comment]
Thanks, worked great!

I would add a check for obj.type == 'MESH' on line 150 as well (still getting errors on empties in selection), but that's a luxury. ;)

**Comment by danielenger** [comment]
Luxury done. :smile:

**Comment by eobet** [comment]
Wonderful, thanks again!

This will be integrated in my current workflow for my game development, and will help very much.

I'll just go ahead and close this issue now, since it's fixed and then some. :)
